export class CashService {

    // 현재 잔고를 확인하는 함수
    checkValue = () => {
        console.log("돈이 있는지 검사합니다.");
        // 구매자 계좌 잔고 검증 코드 (대략 10줄 정도)
        // ...
        // ...
        // ...
        // ...
    }
}