export class PointService {

    // 현재 포인트를 확인하는 함수
    checkValue = () => {
        console.log("포인트가 있는지 검사합니다.");
        // 구매자 포인트 검증 코드 (대략 10줄 정도)
        // ...
        // ...
        // ...
        // ...
    }
}