version: '3.7'

# 컴퓨터 목록
services:
  # 컴퓨터 이름(백엔드 컴퓨터)
  my-backend:
    image: asia-northeast3-docker.pkg.dev/codecamp-backend-422908/my-backend-project-nestjs/nestjs-image:0.4 # 제일 끝에 버전은 계속 업데이트 해주기
    # platform: linux/x86_64 # GCP 컴퓨터와 CPU 다를 경우 이 코드 추가해보기
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    # ports:
    #   - 3000:3000 # 포트포워딩 디폴트 값으로
    # env_file:
    #   - ./.env.prod # prod 환경변수 파일 추가

  # 도커 MySQL이 아닌 Cloud SQL을 DB로 사용할 것이기 때문에 주석 처리
  # 컴퓨터 이름(데이터베이스 컴퓨터)
  # my-database:
  #   # platform: linux/86_64 # 버전, 사양, CPU 문제로 DB 실행 안되면 이 코드 추가해보기
  #   image: mysql:latest # MySQL로 DB 변경
  #   environment:
  #     MYSQL_DATABASE: 'mydocker' # 도커의 MySQL 실행하며 mydocker DB 자동 생성
  #     MYSQL_ROOT_PASSWORD: 'root' # 도커의 MySQL 실행하며 비밀번호로 root 자동 입력
  #   ports:
  #     - 3306:3306 # MySQL 포트번호
