version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./controllers:/myFolder/controllers
      - ./models:/myFolder/models
      - ./swagger:/myFolder/swagger
      - ./utils:/myFolder/utils
      - ./views:/myFolder/views
      - ./index.js:/myFolder/index.js
    ports:
      - 3000:3000

  my-database:
    image: mongo:5
    ports:
      - 27017:27017
