version: "3.7"

services:
    api-gateway:
        image: nginx:latest # Nginx 최신 버전
        volumes: # 로컬의 default.conf 파일과 도커 안의 default.conf 파일 동기화
            - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    auth-service:
        build:
            context: ./services/auth
            dockerfile: Dockerfile
        volumes:
            - ./services/auth/src:/auth-service/src

    stock-service:
        build:
            context: ./services/stock
            dockerfile: Dockerfile
        volumes:
            - ./services/stock/index.js:/stock-service/index.js
